# Generated by Django 5.0.1 on 2024-01-21 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('story_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='story_id')),
                ('story_name', models.CharField(max_length=35, verbose_name='story_name')),
                ('story_isactive', models.BooleanField(default=True, verbose_name='story_is_active')),
                ('story_slug', models.SlugField(unique=True, verbose_name='story_slug')),
            ],
        ),
        migrations.CreateModel(
            name='StoryChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_id', models.PositiveIntegerField(default=1)),
                ('choice_image', models.URLField(default='https://via.placeholder.com/150')),
                ('choice_image_alt', models.TextField(default='image', max_length=255, verbose_name='choice_image_alt_text')),
                ('choice_text', models.TextField()),
                ('prev_choice_sub', models.PositiveIntegerField(default=1)),
                ('prev_choice_txt', models.CharField(default='return', max_length=32)),
                ('next_choice1_add', models.PositiveIntegerField(default=1)),
                ('next_choice1_txt', models.CharField(default='choice 1', max_length=32)),
                ('next_choice2_add', models.PositiveIntegerField(default=1)),
                ('next_choice2_txt', models.CharField(default='choice 2', max_length=32)),
                ('is_checkpoint', models.BooleanField(default=False)),
                ('story_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storyblock.story')),
            ],
            options={
                'unique_together': {('story_id', 'choice_id')},
            },
        ),
    ]
