# Generated by Django 5.0.1 on 2024-02-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyblock', '0003_storyblock_delete_storychoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='story_id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='story id'),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_isactive',
            field=models.BooleanField(default=True, verbose_name='story is active'),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_name',
            field=models.CharField(default='default story name', max_length=35, unique=True, verbose_name='story name'),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_slug',
            field=models.SlugField(default='default-story-slug', unique=True, verbose_name='story slug (URL-friendly nickname)'),
        ),
        migrations.AlterField(
            model_name='storyblock',
            name='block_image_alt',
            field=models.TextField(default='image', max_length=255, verbose_name='storyblock image alt text (screenreader-friendly description)'),
        ),
        migrations.AlterField(
            model_name='storyblock',
            name='block_slug',
            field=models.SlugField(default='block-slug', unique=True, verbose_name='storyblock slug (URL-friendly nickname)'),
        ),
        migrations.AlterField(
            model_name='storyblock',
            name='block_text',
            field=models.TextField(verbose_name='storyblock text'),
        ),
    ]
