# Generated by Django 5.0.1 on 2024-02-01 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storyblock', '0004_alter_story_story_id_alter_story_story_isactive_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Story',
            new_name='oldStory',
        ),
        migrations.RenameModel(
            old_name='StoryBlock',
            new_name='oldStoryBlock',
        ),
    ]
