# Generated by Django 5.0.1 on 2024-02-01 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storyblock', '0006_alter_oldstoryblock_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='oldStory',
        ),
        migrations.DeleteModel(
            name='oldStoryBlock',
        ),
    ]
