BEGIN TRANSACTION;
INSERT INTO "editstory_story" ("story_id","story_name","story_isactive","story_slug") VALUES (1,'the new world',1,'default-story-slug');
INSERT INTO "editstory_storyblock" ("block_id","block_slug","block_image","block_image_alt","block_text","prev_block_txt","next_block1_txt","next_block2_txt","is_checkpoint","story_id_id","next_block1_slug","next_block2_slug","prev_block_slug","is_starting_block","is_ending_block","is_deadend_block") VALUES (1,'tnw-1','http://via.placeholder.com/150','image description of first image','this is the first block in the first story. do you go left or go right?','return','go left','go right',0,1,'tnw-2','tnw-3','tnw-1',1,0,0);
INSERT INTO "editstory_storyblock" ("block_id","block_slug","block_image","block_image_alt","block_text","prev_block_txt","next_block1_txt","next_block2_txt","is_checkpoint","story_id_id","next_block1_slug","next_block2_slug","prev_block_slug","is_starting_block","is_ending_block","is_deadend_block") VALUES (2,'tnw-2','https://via.placeholder.com/150','image','this is the second choice in this story. do you want to go back, go left, or go right from here?','return','go left','go right',0,1,'tnw-1','tnw-3','tnw-1',0,0,0);
INSERT INTO "editstory_storyblock" ("block_id","block_slug","block_image","block_image_alt","block_text","prev_block_txt","next_block1_txt","next_block2_txt","is_checkpoint","story_id_id","next_block1_slug","next_block2_slug","prev_block_slug","is_starting_block","is_ending_block","is_deadend_block") VALUES (3,'tnw-3','https://via.placeholder.com/150','image','this is decision 3','back to the start','go back 1 space','keep going forward',0,1,'tnw-2','tnw-4','tnw-1',0,0,0);
INSERT INTO "editstory_storyblock" ("block_id","block_slug","block_image","block_image_alt","block_text","prev_block_txt","next_block1_txt","next_block2_txt","is_checkpoint","story_id_id","next_block1_slug","next_block2_slug","prev_block_slug","is_starting_block","is_ending_block","is_deadend_block") VALUES (4,'tnw-5','https://via.placeholder.com/150','image','oh no this is a dead end! :(','return','go left','go right',0,1,'block-slug2','block-slug3','tnw-4',0,0,1);
INSERT INTO "editstory_storyblock" ("block_id","block_slug","block_image","block_image_alt","block_text","prev_block_txt","next_block1_txt","next_block2_txt","is_checkpoint","story_id_id","next_block1_slug","next_block2_slug","prev_block_slug","is_starting_block","is_ending_block","is_deadend_block") VALUES (5,'tnw-6','https://via.placeholder.com/150','image','yay this is the end! you did it!','return','go left','go right',0,1,'block-slug2','block-slug3','block-slug',0,1,0);
INSERT INTO "editstory_storyblock" ("block_id","block_slug","block_image","block_image_alt","block_text","prev_block_txt","next_block1_txt","next_block2_txt","is_checkpoint","story_id_id","next_block1_slug","next_block2_slug","prev_block_slug","is_starting_block","is_ending_block","is_deadend_block") VALUES (19,'tnw-4','https://via.placeholder.com/150','image','this is decision 4','return to 1','forward to 6','forward to 5',0,1,'tnw-6','tnw-5','tnw-1',0,0,0);
COMMIT;
