# Generated by Django 5.0.1 on 2024-02-17 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('story_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='story id')),
                ('story_name', models.CharField(default='default story name', max_length=35, unique=True, verbose_name='story name')),
                ('story_isactive', models.BooleanField(default=True, verbose_name='story is active')),
                ('story_slug', models.SlugField(default='default-story-slug', unique=True, verbose_name='story slug (URL-friendly nickname)')),
            ],
            options={
                'verbose_name_plural': 'stories',
            },
        ),
        migrations.CreateModel(
            name='StoryBlock',
            fields=[
                ('block_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='storyblock id')),
                ('block_slug', models.SlugField(default='block-slug', unique=True, verbose_name='new storyblock slug (URL-friendly nickname)')),
                ('block_image', models.URLField(default='https://via.placeholder.com/150', verbose_name='new storyblock image URL')),
                ('block_image_alt', models.TextField(default='image', max_length=255, verbose_name='new storyblock image alt text (screenreader-friendly description)')),
                ('block_text', models.TextField(default='text', verbose_name='new storyblock text')),
                ('prev_block_slug', models.SlugField(blank=True, default='block-slug', null=True, verbose_name='previous storyblock slug')),
                ('prev_block_txt', models.CharField(blank=True, default='return', max_length=32, null=True, verbose_name='previous storyblock button text')),
                ('next_block1_slug', models.SlugField(blank=True, default='block-slug', null=True, verbose_name='choice 1 storyblock slug')),
                ('next_block1_txt', models.CharField(blank=True, default='go left', max_length=32, null=True, verbose_name='choice 1 button text')),
                ('next_block2_slug', models.SlugField(blank=True, default='block-slug', null=True, verbose_name='choice 2 storyblock slug')),
                ('next_block2_txt', models.CharField(blank=True, default='go right', max_length=32, null=True, verbose_name='choice 2 button text')),
                ('is_starting_block', models.BooleanField(default=False)),
                ('is_ending_block', models.BooleanField(default=False)),
                ('is_deadend_block', models.BooleanField(default=False)),
                ('story_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editstory.story')),
            ],
            options={
                'verbose_name_plural': 'story blocks',
            },
        ),
        migrations.AddConstraint(
            model_name='storyblock',
            constraint=models.UniqueConstraint(condition=models.Q(('is_starting_block', True)), fields=('story_id',), name='one_starting_block_per_story'),
        ),
        migrations.AddConstraint(
            model_name='storyblock',
            constraint=models.UniqueConstraint(condition=models.Q(('is_ending_block', True)), fields=('story_id',), name='one_ending_block_per_story'),
        ),
        migrations.AlterUniqueTogether(
            name='storyblock',
            unique_together={('story_id', 'block_id')},
        ),
    ]
