# Generated by Django 5.0.1 on 2024-02-02 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editstory', '0002_remove_storyblock_next_block1_add_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyblock',
            name='block_image',
            field=models.URLField(default='https://via.placeholder.com/150', verbose_name='new storyblock image URL'),
        ),
        migrations.AlterField(
            model_name='storyblock',
            name='block_image_alt',
            field=models.TextField(default='image', max_length=255, verbose_name='new storyblock image alt text (screenreader-friendly description)'),
        ),
        migrations.AlterField(
            model_name='storyblock',
            name='block_slug',
            field=models.SlugField(default='block-slug', unique=True, verbose_name='new storyblock slug (URL-friendly nickname)'),
        ),
        migrations.AlterField(
            model_name='storyblock',
            name='block_text',
            field=models.TextField(default='text', verbose_name='new storyblock text'),
        ),
        migrations.AlterField(
            model_name='storyblock',
            name='prev_block_txt',
            field=models.CharField(default='return', max_length=32, verbose_name='previous storyblock button text'),
        ),
    ]
