# Generated by Django 5.0.1 on 2024-02-02 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editstory', '0005_alter_storyblock_next_block1_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name_plural': 'stories'},
        ),
        migrations.AlterModelOptions(
            name='storyblock',
            options={'verbose_name_plural': 'story blocks'},
        ),
    ]
