# Generated by Django 5.0.1 on 2024-02-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editstory', '0007_remove_storyblock_id_alter_storyblock_block_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyblock',
            name='is_starting_block',
            field=models.BooleanField(default=False),
        ),
    ]
