# Generated by Django 5.0.1 on 2024-02-16 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editstory', '0008_storyblock_is_starting_block'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='storyblock',
            constraint=models.UniqueConstraint(condition=models.Q(('is_starting_block', True)), fields=('story_id',), name='one_starting_block_per_story'),
        ),
    ]
