# Generated by Django 5.0.1 on 2024-02-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editstory', '0009_storyblock_one_starting_block_per_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyblock',
            name='is_ending_block',
            field=models.BooleanField(default=False),
        ),
    ]
