# Generated by Django 5.0.1 on 2024-02-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editstory', '0010_storyblock_is_ending_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyblock',
            name='is_deadend_block',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='storyblock',
            constraint=models.UniqueConstraint(condition=models.Q(('is_ending_block', True)), fields=('story_id',), name='one_ending_block_per_story'),
        ),
    ]
